name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: devsecops-webapp

jobs:

  security:
    name: Security Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: fs
          scan-ref: .
          severity: CRITICAL,HIGH
          exit-code: 1

  build-push:
    name: Build and Push
    needs: security
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Set ECR Registry
        run: |
          AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
          echo "ECR_REGISTRY=${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com" >> "$GITHUB_ENV"

      - name: Build Image
        run: |
          docker build \
            -t devsecops-webapp:${{ github.sha }} .

      - name: Trivy Image Scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: 'devsecops-webapp:${{ github.sha }}'
          severity: CRITICAL,HIGH
          exit-code: 1

      - name: Tag and Push Image
        run: |
          IMAGE_URI="${ECR_REGISTRY}/${ECR_REPOSITORY}:${{ github.sha }}"

          echo "IMAGE_URI=$IMAGE_URI"

          docker tag \
            devsecops-webapp:${{ github.sha }} \
            "$IMAGE_URI"

          docker push "$IMAGE_URI"

  deploy:
    name: Deploy to EKS
    needs: build-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Configure kubectl
        run: |
          aws eks update-kubeconfig \
            --region $AWS_REGION \
            --name devops-eks-project4

      - name: Deploy
        run: |
          sed -i \
          "s|IMAGE_PLACEHOLDER|${{ env.ECR_REGISTRY }}/${{ env.ECR_REPOSITORY }}:${{ github.sha }}|" \
          k8s/deployment.yaml

          kubectl apply -f k8s/deployment.yaml

      - name: Wait for Deployment
        run: |
          kubectl rollout status \
            deployment/devsecops-webapp \
            --timeout=180s
